### ISSUE TITLE
Error when installing the mod

### ISSUE THREAD

**Issue by gutolimeira** [CPlayxs/More-Fauna-And-Flora#10]
When you try to install, the installation completed message appears, but the mod is not actually installed:

![Installation](https://user-images.githubusercontent.com/64593191/193424365-81fabe72-4f73-48b1-bfca-018f9ffcc8e0.png)
![ModMissing](https://user-images.githubusercontent.com/64593191/193424368-93e65b0c-d4c4-4996-aa1b-714ecf16b685.png)

**Comment by CPlayxs** [comment]
try now!

**Comment by gutolimeira** [comment]
Working perfectly!
