### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by gutolimeira** [CPlayxs/More-Fauna-And-Flora#4]
I would like to translate to Portuguese, is there any way?

**Comment by shannaurelle** [comment]
Yes, there is. I will send a pull request here so this mod will also have translations :>

**Comment by CPlayxs** [comment]
> I would like to translate to Portuguese, is there any way?

the pull request with the Portuguese translation basic code is merged! now you can fork this repository and write the translation and then make a pull request
